### PR TITLE
CI/CD workflow for GitHub Actions

### PR DESCRIPTION
**Pull request by sergeuz**
This PR add a CI/CD workflow config for GitHub Actions.

### CODE REVIEW

**Review by joegoggins — CHANGES_REQUESTED** [review]
Sweet! Great to see some test coverage emerge for this increasingly critical tool. Thanks Sergey.

Could you follow the same requests for change I mentioned in:
https://github.com/particle-iot/device-os-test-runner/pull/4
https://app.shortcut.com/particle/story/91839/setup-device-os-test-runner-to-run-linter-tests-in-circleci#activity-92870

i.e. drop node 14 and 16, enforce with `nyc --check-coverage` (whatever number that passes for now), etc

**Review by joegoggins — APPROVED** [review]
Thanks Sergey, LTGM.

Note that this test may fail due to GitHub rate limits, on my third run of `npm test`, I observed this:


```
npm test

> @particle/device-os-flash-util@0.7.0 test /Users/jgoggins/git/particle/device-os-flash-util
> npm run lint -- --quiet && npm run coverage


> @particle/device-os-flash-util@0.7.0 lint /Users/jgoggins/git/particle/device-os-flash-util
> eslint . "--quiet"


> @particle/device-os-flash-util@0.7.0 coverage /Users/jgoggins/git/particle/device-os-flash-util
> nyc --check-coverage npm run test:unit


> @particle/device-os-flash-util@0.7.0 test:unit /Users/jgoggins/git/particle/device-os-flash-util
> mocha --forbid-only "lib/**/*.test.js" --timeout 30000



  ModuleCache (module.js)
Downloading release binaries
    1) can instantiate it and download all release modules associated with Device OS 2.1.0


  0 passing (245ms)
  1 failing

  1) ModuleCache (module.js)
       can instantiate it and download all release modules associated with Device OS 2.1.0:
     HttpError: API rate limit exceeded for 72.50.214.57. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
      at /Users/jgoggins/git/particle/device-os-flash-util/node_modules/@octokit/request/dist-node/index.js:86:21
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async ModuleCache._downloadRelease (lib/module.js:10:3534)
      at async ModuleCache.getReleaseModules (lib/module.js:2:3051)
      at async Context.<anonymous> (lib/module.test.js:47:23)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @particle/device-os-flash-util@0.7.0 test:unit: `mocha --forbid-only "lib/**/*.test.js" --timeout 30000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @particle/device-os-flash-util@0.7.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgoggins/.npm/_logs/2021-12-03T15_51_59_446Z-debug.log
```

I'd rather not worry about mocking this out now though because we can address it later and more easily once device-os-flash-util is using the new device-os-release npm module being developed here https://github.com/particle-iot/cli/pull/60

**Comment by joegoggins** [comment]
@mstan , wanted you to be aware of this device-os-flash-util PR as well; at some point when [device-os-release module](https://github.com/particle-iot/cli/pull/60) is ready, I'm hoping you can pair with Sergey to utilize this module in this project. I bet it'd be worthwhile to include Sergey on the PR review of that as well to confirm that it will be readily usage here.

**Comment by sergeuz** [comment]
> Note that this test may fail due to GitHub rate limits

Yeah, we probably shouldn't be downloading actual binaries in unit tests. I'll see if I can refactor the tests next time I get my hands on this repo.

**Pull request merged**
