### PR TITLE
Use platform definitions from device-constants

### PR DESCRIPTION
**Pull request by sergeuz**
This PR introduces the following changes:

- Use device-constants instead of own platform definitions.
- Remove the unused factory reset feature in order to avoid hardcoding DCT and filesystem addresses in device-constants.

#### Steps to test

Flashing via DFU and OpenOCD should work as expected.

#### References

- [sc-98439](https://app.shortcut.com/particle/story/98439/move-definitions-specific-to-device-os-flash-util-to-device-constants-npm-module)
- [device-constants#20](https://github.com/particle-iot-inc/device-constants/pull/20)

### CODE REVIEW

**Comment by avtolstoy** [comment]
As discussed I'm going to kick-off a test job on Concourse to validate that these changes don't break anything across all of our platforms.

**Review by joegoggins — APPROVED** [review]
I would have loved to see updates to automated tests as part of this change to illustrate concretely that key things didn't break. For example, I wrote [these tests](https://github.com/particle-iot/device-os-test-runner/commit/55b7eb5b056baea3d503c4b97eab7ad3746249cf) while refactoring platform.js in device-os-test-runner to show my changes worked as intended. Maybe in the future, we can bias toward that development approach. Not a blocker to merging, but worth naming that not having this makes reviewing more difficult as well as making subsequent releases for this more risky.

To build confidence that this changes still works I restored an Argon at 3.2.0 to 2.3.0 via this

command: `node lib/index.js 2.3.0 -d e00fce688ad9fc84c07d6b2e`

output:

```
Initializing module cache
Found cached module binaries
Initializing flash interface
Enumerating local devices
Flashing target devices
Target devices:
1. e00fce688ad9fc84c07d6b2e (Argon)
[Device 1] Preparing device for flashing
[Device 1] Flashing argon-softdevice@2.3.0.bin
[Device 1] Flashing argon-system-part1@2.3.0.bin
[Device 1] Flashing argon-tinker@2.3.0.bin
[Device 1] Resetting device
[Device 1] Using control requests to flash remaining modules
[Device 1] Preparing device for flashing
[Device 1] Flashing argon-bootloader@2.3.0.bin
[Device 1] Preparing device for flashing
[Device 1] Flashing argon-ncp-firmware@0.0.5.bin
[Device 1] Flashed successfully
Done
```

👍

**Review by busticated — APPROVED** [review]

**Comment by sergeuz** [comment]
> I would have loved to see updates to automated tests as part of this change to illustrate concretely that key things didn't break.

Ah, good point. I'll add tests at least for the new `Platform` class. Unfortunately, having a decent test coverage was never a priority as this tool started as a personal fun project and then was adapted to address our immediate needs. I suggest we cover this codebase with tests properly as part of moving it over to the new CLI.

**Comment by joegoggins** [comment]
Hi there @sergeuz, in sprint review we marked this "Move platform-specific definitions required by device-os-flash-util to device-constants" MISO to done; under the thinking that all you needed to do is merge this and cut a release. Could you take care of that first thing next week?

**Comment by sergeuz** [comment]
@joegoggins Sorry, this PR got delayed by some additional changes in device-constants for P2. I'll merge it now and release a new version.

**Pull request merged**
